/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/stickmod.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stickmod.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, 12, 0]} scale={2}>
        <mesh geometry={nodes.sitck_1.geometry} material={nodes.sitck_1.material} position={[-17.621, 0, 15.706]}>
          <mesh geometry={nodes.bubble_1.geometry} material={nodes.bubble_1.material} position={[0, -51.947, 0]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/stickmod.glb')
